### PR TITLE
Some additional helper functions

### PR DESCRIPTION
**Pull request by wuaalb**
Extracted log-sum-exp from examples and added a log normal pdf parameterized with variance.
Also changed `sd` to `std` and `eps` to `epsilon` for consistency with lasagne and numpy.

### CODE REVIEW

**Comment by casperkaae** [comment]
Hi

Looks good with the log-sum-exp and the sd->std. I'm not sure we should change the interface again for the eps->epsilon again though?

Casper

**Comment by wuaalb** [comment]
Was just for coherence with `lasagne.layers.BatchNormLayer` or `lasagne.updates.adagrad` for instance, but yeah, maybe it's too late now..
Lemme know if I should revert that change..

**Comment by casperkaae** [comment]
Hi again

yes I think we should revert the epsilon change (If you do not strongly object), otherwise I think it looks great!

**Comment by wuaalb** [comment]
I've changed back to `eps`.

I changed the docstrings to clarify what `eps` does exactly for each function, as it depends slightly on the parameterization used. There were also some `T.log()`s that didn't use `eps`.

Also added `normal1` versions of the closed-form KL-divergences.

**Pull request merged**
