### PR TITLE
add seed option to sample layers

### PR DESCRIPTION
**Pull request by casperkaae**
add seed option to SampleLayer and SimpleSampleLayer init

### CODE REVIEW

**Comment by wuaalb** [comment]
Additionally, could we add a function to re-seed existing instances?
```python
def seed(self, seed=None):
   self._srng.seed(seed)
```
(I don't know how to make changes to your PR on github)

I may

1. Instantiate model
2. Train
3. Save weights
4. Re-seed
5. Use for something (e.g. compute log likelihood, ..)
6. Re-seed
7. Use for something else

Or

1. Instantiate model
2. Load weights
3. Re-seed
4. Use for something (e.g. compute log likelihood, ..)

In those cases I don't want to create new instances of the model just to fix the RNG seed..

**Comment by casperkaae** [comment]
ok, better now?

**Comment by wuaalb** [comment]
Great, thanks.

**Comment by casperkaae** [comment]
merged #31

**Pull request merged**
